from pathlib import Path


def replace_once(path, old, new):
    p = Path(path)
    text = p.read_text()
    if text.count(old) != 1:
        raise SystemExit(f"guard failed for {path}: expected one occurrence, got {text.count(old)}")
    p.write_text(text.replace(old, new, 1))

sheet = "shared/src/commonMain/kotlin/io/github/mrsimkin/dndcustomaid/shared/character/CharacterSheet.kt"
replace_once(sheet, '''@Serializable\ndata class CharacterSpellcastingSource(\n    val id: Uuid,\n    val name: String,\n    val linkedClassId: Uuid?,\n    val sortOrder: Int,\n)\n''', '''@Serializable\nenum class CharacterSpellcastingOriginKind {\n    CLASS,\n    TRAIT,\n    RACE,\n    BACKGROUND,\n    FEAT,\n    ITEM,\n    MAGIC_ITEM,\n    GIFT,\n    OTHER,\n}\n\n@Serializable\ndata class CharacterSpellcastingSource(\n    val id: Uuid,\n    val name: String,\n    val linkedClassId: Uuid?,\n    val sortOrder: Int,\n    val originKind: CharacterSpellcastingOriginKind = if (linkedClassId != null) {\n        CharacterSpellcastingOriginKind.CLASS\n    } else {\n        CharacterSpellcastingOriginKind.OTHER\n    },\n    val originReferenceId: Uuid? = null,\n)\n''')

sq = "shared/src/commonMain/sqldelight/io/github/mrsimkin/dndcustomaid/shared/db/Character.sq"
replace_once(sq, '''CREATE TABLE character_spell_source (\n    id TEXT NOT NULL PRIMARY KEY,\n    character_id TEXT NOT NULL REFERENCES character(id) ON DELETE CASCADE,\n    name TEXT NOT NULL,\n    linked_class_id TEXT,\n    sort_order INTEGER NOT NULL,\n    UNIQUE(character_id, sort_order)\n);\n''', '''CREATE TABLE character_spell_source (\n    id TEXT NOT NULL PRIMARY KEY,\n    character_id TEXT NOT NULL REFERENCES character(id) ON DELETE CASCADE,\n    name TEXT NOT NULL,\n    linked_class_id TEXT,\n    sort_order INTEGER NOT NULL,\n    origin_kind TEXT NOT NULL DEFAULT 'OTHER',\n    origin_reference_id TEXT,\n    UNIQUE(character_id, sort_order)\n);\n''')
replace_once(sq, '''insertCharacterSpellSource:\nINSERT INTO character_spell_source(id, character_id, name, linked_class_id, sort_order)\nVALUES (?, ?, ?, ?, ?);\n\nselectCharacterSpellSources:\nSELECT id, character_id, name, linked_class_id, sort_order\nFROM character_spell_source\n''', '''insertCharacterSpellSource:\nINSERT INTO character_spell_source(\n    id, character_id, name, linked_class_id, sort_order, origin_kind, origin_reference_id\n)\nVALUES (?, ?, ?, ?, ?, ?, ?);\n\nselectCharacterSpellSources:\nSELECT id, character_id, name, linked_class_id, sort_order, origin_kind, origin_reference_id\nFROM character_spell_source\n''')

Path("shared/src/commonMain/sqldelight/io/github/mrsimkin/dndcustomaid/shared/db/13.sqm").write_text('''ALTER TABLE character_spell_source\nADD COLUMN origin_kind TEXT NOT NULL DEFAULT 'OTHER';\n\nALTER TABLE character_spell_source\nADD COLUMN origin_reference_id TEXT;\n\nUPDATE character_spell_source\nSET origin_kind = 'CLASS'\nWHERE linked_class_id IS NOT NULL;\n''')

repo = "shared/src/commonMain/kotlin/io/github/mrsimkin/dndcustomaid/shared/character/CharacterRepository.kt"
replace_once(repo, '''        val normalizedSources = sheet.spellcastingSources.map { source ->\n            source.copy(linkedClassId = source.linkedClassId?.takeIf { it in classIdSet })\n        }\n''', '''        val traitIds = sheet.traits.mapTo(mutableSetOf()) { it.id }\n        val featIds = sheet.traits.filter { it.type == CharacterTraitType.FEAT }.mapTo(mutableSetOf()) { it.id }\n        val giftIds = sheet.traits.filter { it.type == CharacterTraitType.GIFT_BLESSING }.mapTo(mutableSetOf()) { it.id }\n        val inventoryIds = sheet.inventoryItems.mapTo(mutableSetOf()) { it.id }\n        val normalizedSources = sheet.spellcastingSources.map { source ->\n            val linkedClassId = if (source.originKind == CharacterSpellcastingOriginKind.CLASS) {\n                source.linkedClassId?.takeIf { it in classIdSet }\n            } else {\n                null\n            }\n            val referenceId = when (source.originKind) {\n                CharacterSpellcastingOriginKind.TRAIT -> source.originReferenceId?.takeIf { it in traitIds }\n                CharacterSpellcastingOriginKind.FEAT -> source.originReferenceId?.takeIf { it in featIds }\n                CharacterSpellcastingOriginKind.GIFT -> source.originReferenceId?.takeIf { it in giftIds }\n                CharacterSpellcastingOriginKind.ITEM,\n                CharacterSpellcastingOriginKind.MAGIC_ITEM,\n                -> source.originReferenceId?.takeIf { it in inventoryIds }\n                else -> null\n            }\n            source.copy(linkedClassId = linkedClassId, originReferenceId = referenceId)\n        }\n''')
replace_once(repo, '''            normalizedSources.forEachIndexed { index, source ->\n                database.characterQueries.insertCharacterSpellSource(source.id.toString(), sheet.id.toString(), source.name.trim(), source.linkedClassId?.toString(), index.toLong())\n            }\n''', '''            normalizedSources.forEachIndexed { index, source ->\n                database.characterQueries.insertCharacterSpellSource(\n                    id = source.id.toString(),\n                    character_id = sheet.id.toString(),\n                    name = source.name.trim(),\n                    linked_class_id = source.linkedClassId?.toString(),\n                    sort_order = index.toLong(),\n                    origin_kind = source.originKind.name,\n                    origin_reference_id = source.originReferenceId?.toString(),\n                )\n            }\n''')
replace_once(repo, '''        val spellcastingSources = database.characterQueries.selectCharacterSpellSources(core.id.toString()) { id, _, name, linkedClassId, sortOrder ->\n            val parsed = linkedClassId?.let { runCatching { Uuid.parse(it) }.getOrNull() }?.takeIf { it in classIdSet }\n            CharacterSpellcastingSource(Uuid.parse(id), name, parsed, sortOrder.toInt())\n        }.executeAsList()\n''', '''        val spellcastingSources = database.characterQueries.selectCharacterSpellSources(core.id.toString()) {\n                id, _, name, linkedClassId, sortOrder, originKind, originReferenceId ->\n            val parsedClass = linkedClassId?.let { runCatching { Uuid.parse(it) }.getOrNull() }?.takeIf { it in classIdSet }\n            val parsedKind = runCatching { CharacterSpellcastingOriginKind.valueOf(originKind) }.getOrElse {\n                if (parsedClass != null) CharacterSpellcastingOriginKind.CLASS else CharacterSpellcastingOriginKind.OTHER\n            }\n            val parsedReference = originReferenceId?.let { runCatching { Uuid.parse(it) }.getOrNull() }\n            CharacterSpellcastingSource(\n                id = Uuid.parse(id),\n                name = name,\n                linkedClassId = parsedClass,\n                sortOrder = sortOrder.toInt(),\n                originKind = parsedKind,\n                originReferenceId = parsedReference,\n            )\n        }.executeAsList()\n''')

Path("shared/src/commonTest/kotlin/io/github/mrsimkin/dndcustomaid/shared/character/CharacterSpellcastingOriginTest.kt").write_text('''package io.github.mrsimkin.dndcustomaid.shared.character\n\nimport kotlin.test.Test\nimport kotlin.test.assertEquals\nimport kotlin.test.assertNull\nimport kotlin.uuid.Uuid\n\nclass CharacterSpellcastingOriginTest {\n    @Test\n    fun legacyLinkedClassSourceDefaultsToClassOrigin() {\n        val classId = Uuid.random()\n        val source = CharacterSpellcastingSource(\n            id = Uuid.random(),\n            name = "Paladín",\n            linkedClassId = classId,\n            sortOrder = 0,\n        )\n        assertEquals(CharacterSpellcastingOriginKind.CLASS, source.originKind)\n        assertEquals(classId, source.linkedClassId)\n        assertNull(source.originReferenceId)\n    }\n\n    @Test\n    fun legacyUnlinkedSourceDefaultsToOtherOrigin() {\n        val source = CharacterSpellcastingSource(\n            id = Uuid.random(),\n            name = "Fuente heredada",\n            linkedClassId = null,\n            sortOrder = 0,\n        )\n        assertEquals(CharacterSpellcastingOriginKind.OTHER, source.originKind)\n    }\n\n    @Test\n    fun canonicalOriginKindsKeepOwnerOrder() {\n        assertEquals(\n            listOf(\n                CharacterSpellcastingOriginKind.CLASS,\n                CharacterSpellcastingOriginKind.TRAIT,\n                CharacterSpellcastingOriginKind.RACE,\n                CharacterSpellcastingOriginKind.BACKGROUND,\n                CharacterSpellcastingOriginKind.FEAT,\n                CharacterSpellcastingOriginKind.ITEM,\n                CharacterSpellcastingOriginKind.MAGIC_ITEM,\n                CharacterSpellcastingOriginKind.GIFT,\n                CharacterSpellcastingOriginKind.OTHER,\n            ),\n            CharacterSpellcastingOriginKind.entries,\n        )\n    }\n}\n''')
