from pathlib import Path

path = Path('docs/PROJECT_STATE.md')
text = path.read_text(encoding='utf-8')

old_header = "**Active focused closure branch:** `implementation/phase4-character-closure`  \n**Current phase:** Phase 4 Character Foundation Closure  "
new_header = "**Durable pre-QA branch:** `implementation/phase4-preqa-consolidation`\n**Current phase:** Phase 4 Character Foundation Closure — owner QA pending"
if old_header not in text:
    raise SystemExit('expected PROJECT_STATE header seam not found')
text = text.replace(old_header, new_header, 1)

old_resume = "## 0. Primary resume order\n\n1. `docs/checkpoints/2026-09-04_PHASE4_BATCH_M5_PREQA_CONSOLIDATION.md` — controlling pre-QA closure checkpoint; M5 GREEN, exact replacement QA candidate frozen and independently validated;\n2. `docs/checkpoints/2026-09-04_PHASE4_BATCH_M4_INTER_BATCH_SCOPE_HOLE_CLOSURE_PLAN.md` — repair plan whose six approved-scope holes are now implemented and closed;\n3. `docs/checkpoints/2026-09-04_PHASE4_BATCH_M3_PRIOR_BATCH_COMPLETENESS_AUDIT.md` — historical implementation-completeness audit that established the inter-batch holes;\n4. `docs/checkpoints/2026-09-04_PHASE4_BATCH_M2_CODE_HEALTH_AUDIT.md` — code-health/static architecture audit that bounded the M5 cleanup;\n5. `docs/checkpoints/2026-09-04_PHASE4_BATCH_M1_SCOPE_TRACEABILITY_AUDIT.md` — D-0047 scope traceability audit;\n6. `docs/checkpoints/2026-09-04_PHASE4_BATCH_L_FROZEN_QA_CANDIDATE.md` — historical pre-M frozen candidate; preserve unchanged as evidence only, not the active M6 candidate;\n7. `docs/checkpoints/2026-09-04_PHASE4_BATCH_K_STABILIZATION_COMPLETE.md` — owner-schema migration proof;\n8. `docs/checkpoints/2026-09-04_PHASE4_BATCH_J_BACKUP_IMPORT_COMPLETE.md` — completed backup/import gate;\n9. `docs/checkpoints/2026-09-04_PHASE4_BATCH_I2B_TABLE_MODE.md` — completed Batch I closure;\n10. `docs/decisions/D-0047_PHASE4_CHARACTER_CLOSURE_EXPANSION.md` and `docs/checkpoints/2026-09-03_PHASE4_CLOSURE_EXECUTION_BATCH_PLAN.md` — controlling approved scope and historical execution decomposition."
new_resume = "## 0. Primary resume order\n\n1. `docs/checkpoints/2026-09-04_PHASE4_M6_QA_PAUSE_HANDOFF.md` — current practical resume checkpoint; M6 is ready but owner QA has not started;\n2. `docs/checkpoints/2026-09-04_PHASE4_BATCH_M5_PREQA_CONSOLIDATION.md` — controlling pre-QA closure evidence; M5 GREEN, exact replacement QA candidate frozen and independently validated;\n3. `docs/checkpoints/2026-09-04_PHASE4_BATCH_M4_INTER_BATCH_SCOPE_HOLE_CLOSURE_PLAN.md` — repair plan whose six approved-scope holes are now implemented and closed;\n4. `docs/checkpoints/2026-09-04_PHASE4_BATCH_M3_PRIOR_BATCH_COMPLETENESS_AUDIT.md` — historical implementation-completeness audit that established the inter-batch holes;\n5. `docs/checkpoints/2026-09-04_PHASE4_BATCH_M2_CODE_HEALTH_AUDIT.md` — code-health/static architecture audit that bounded the M5 cleanup;\n6. `docs/checkpoints/2026-09-04_PHASE4_BATCH_M1_SCOPE_TRACEABILITY_AUDIT.md` — D-0047 scope traceability audit;\n7. `docs/checkpoints/2026-09-04_PHASE4_BATCH_L_FROZEN_QA_CANDIDATE.md` — historical pre-M frozen candidate; preserve unchanged as evidence only, not the active M6 candidate;\n8. `docs/checkpoints/2026-09-04_PHASE4_BATCH_K_STABILIZATION_COMPLETE.md` — owner-schema migration proof;\n9. `docs/checkpoints/2026-09-04_PHASE4_BATCH_J_BACKUP_IMPORT_COMPLETE.md` — completed backup/import gate;\n10. `docs/checkpoints/2026-09-04_PHASE4_BATCH_I2B_TABLE_MODE.md` — completed Batch I closure;\n11. `docs/decisions/D-0047_PHASE4_CHARACTER_CLOSURE_EXPANSION.md` and `docs/checkpoints/2026-09-03_PHASE4_CLOSURE_EXECUTION_BATCH_PLAN.md` — controlling approved scope and historical execution decomposition."
if old_resume not in text:
    raise SystemExit('expected PROJECT_STATE resume-order seam not found')
text = text.replace(old_resume, new_resume, 1)

path.write_text(text, encoding='utf-8')
print('PROJECT_STATE pause handoff patch applied')
