package io.github.mrsimkin.dndcustomaid.desktop

import java.awt.Color
import java.awt.image.BufferedImage
import java.io.File
import javax.imageio.ImageIO
import kotlin.test.Test
import kotlin.test.assertEquals
import kotlin.test.assertFalse
import kotlin.test.assertTrue
import org.apache.pdfbox.Loader
import org.apache.pdfbox.multipdf.LayerUtility
import org.apache.pdfbox.pdmodel.PDDocument
import org.apache.pdfbox.pdmodel.PDPage
import org.apache.pdfbox.pdmodel.PDPageContentStream
import org.apache.pdfbox.pdmodel.common.PDRectangle
import org.apache.pdfbox.pdmodel.graphics.form.PDFormXObject
import org.apache.pdfbox.rendering.ImageType
import org.apache.pdfbox.rendering.PDFRenderer
import org.apache.pdfbox.text.PDFTextStripper

/**
 * Complete owner-review proof for the Custom-v1 visual family.
 *
 * The five owner-approved Run-7 base pages are generated by the frozen Run-7 QA fixture and then
 * preserved pixel-identically. Six generated purpose-specific extension pages are appended using
 * the owner-authored v1 paper grammar: centered section headings, alternating gray writing bands,
 * thin rules, compact lookup values and generous writable capacity.
 */
class DesktopPcSheetCustomV1ExtendedFamilyRun1Test {
    private val overflowDiagnostics = mutableListOf<String>()

    @Test
    fun rendersCompleteCustomV1FamilyWithAllExtensionRoles() {
        overflowDiagnostics.clear()
        val proofDir = File(requireNotNull(System.getProperty("pcSheetProofDir"))).apply { mkdirs() }

        // Generate the exact approved five-page Run-7 baseline rather than reimplementing it here.
        DesktopPcSheetHybridStrategyRun7Test().rendersCompleteFivePageAllHybridCustomV1Draft()
        val approvedBase = File(proofDir, "hybrid-strategy1-run7-composite.pdf")
        assertTrue(approvedBase.isFile)

        val baselineRenders = Loader.loadPDF(approvedBase).use { doc ->
            val renderer = PDFRenderer(doc)
            (0 until 5).map { renderer.renderImageWithDPI(it, BASELINE_COMPARE_DPI, ImageType.RGB) }
        }

        val output = File(proofDir, "custom-v1-complete-family-extended-run1.pdf")
        val sourceBytes = resource(TEMPLATE).use { it.readBytes() }

        Loader.loadPDF(approvedBase).use { doc ->
            Loader.loadPDF(sourceBytes).use { source ->
                val logoForm = LayerUtility(doc).importPageAsForm(source, 4)
                val fonts = DesktopPdfFontRegistry(doc, CUSTOM_V1_EXTENSION_THEME)
                val p = DesktopPdfRenderingPrimitives(fonts)

                drawCustomStatistics(doc, p, logoForm)
                drawTraits(doc, p, logoForm)
                drawResources(doc, p, logoForm)
                drawInventory(doc, p, logoForm)
                drawSpells(doc, p, logoForm)
                drawNotes(doc, p, logoForm)
            }
            doc.save(output)
        }

        Loader.loadPDF(output).use { doc ->
            assertEquals(11, doc.numberOfPages)
            assertFalse(doc.isEncrypted)
            repeat(doc.numberOfPages) { index ->
                assertEquals(W, doc.getPage(index).mediaBox.width, 0.01f)
                assertEquals(H, doc.getPage(index).mediaBox.height, 0.01f)
            }

            val extracted = PDFTextStripper().getText(doc)
            listOf(
                "EXTENSIÓN - ESTADÍSTICAS PERSONALIZADAS",
                "EXTENSIÓN - RASGOS Y CARACTERÍSTICAS",
                "EXTENSIÓN - RECURSOS Y OPCIONES",
                "EXTENSIÓN - INVENTARIO / EQUIPO",
                "EXTENSIÓN - CONJUROS",
                "EXTENSIÓN - NOTAS",
            ).forEach { title ->
                assertTrue(extracted.contains(title), "Missing Custom-v1 extension title: $title")
            }

            val renderer = PDFRenderer(doc)
            repeat(11) { index ->
                val image = renderer.renderImageWithDPI(index, 180f, ImageType.RGB)
                assertTrue(
                    ImageIO.write(
                        image,
                        "png",
                        File(proofDir, "custom-v1-complete-family-extended-run1-page-${index + 1}.png"),
                    ),
                )
            }

            // Appending extensions must not change one pixel of the frozen five-page baseline.
            repeat(5) { index ->
                val finalImage = renderer.renderImageWithDPI(index, BASELINE_COMPARE_DPI, ImageType.RGB)
                assertImagesEqual(
                    baselineRenders[index],
                    finalImage,
                    "Frozen Custom-v1 base page ${index + 1} changed while adding extensions.",
                )
            }
        }

        if (overflowDiagnostics.isNotEmpty()) {
            File(proofDir, "custom-v1-complete-family-extended-run1-overflows.txt")
                .writeText(overflowDiagnostics.joinToString("\n"))
        }
        check(overflowDiagnostics.isEmpty()) {
            "Custom-v1 Extended Run 1 text overflow(s):\n" + overflowDiagnostics.joinToString("\n")
        }
        assertTrue(output.length() > 20_000L)
    }

    private fun drawCustomStatistics(doc: PDDocument, p: DesktopPdfRenderingPrimitives, logo: PDFormXObject) {
        val page = extensionPage(doc)
        PDPageContentStream(doc, page).use { s ->
            extensionHeader(s, p, logo, "EXTENSIÓN - ESTADÍSTICAS PERSONALIZADAS", "Aster Vale")

            val x = listOf(24f, 216f, 408f)
            customAttribute(
                s, p, x[0], 112f, 180f, "HONOR", "HON", "15", "+2", "+5", Training.PROFICIENT,
                listOf(
                    SkillRow("Etiqueta cortesana", "+5", Training.PROFICIENT),
                    SkillRow("Reputación", "+5", Training.PROFICIENT),
                ),
                "Prestigio, deber y posición social.",
            )
            customAttribute(
                s, p, x[1], 112f, 180f, "RESOLUCIÓN", "RES", "12", "+1", "+1", Training.NONE,
                listOf(
                    SkillRow("Concentración", "+4", Training.PROFICIENT),
                    SkillRow("Resistir miedo", "+4", Training.PROFICIENT),
                ),
                "Autocontrol ante presión o terror.",
            )
            customAttribute(
                s, p, x[2], 112f, 180f, "SUERTE", "SUE", "18", "+4", "+7", Training.PROFICIENT,
                listOf(
                    SkillRow("Lectura de fortuna", "+7", Training.PROFICIENT),
                    SkillRow("Escape improvisado", "+10", Training.EXPERTISE),
                ),
                "Azar favorable y oportunidades inesperadas.",
            )

            sectionTitle(s, p, 24f, 438f, 564f, "HABILIDADES PERSONALIZADAS VINCULADAS A ATRIBUTOS ESTÁNDAR")
            linkedSkillColumn(
                s, p, 24f, 470f, 180f, "INTELIGENCIA (INT)",
                listOf(
                    SkillRow("Cifras antiguas", "+7", Training.PROFICIENT),
                    SkillRow("Análisis de runas", "+7", Training.PROFICIENT),
                ),
            )
            linkedSkillColumn(
                s, p, 216f, 470f, 180f, "SABIDURÍA (SAB)",
                listOf(
                    SkillRow("Cartografía de campo", "+4", Training.PROFICIENT),
                    SkillRow("Orientación astral", "+1", Training.NONE),
                ),
            )
            linkedSkillColumn(
                s, p, 408f, 470f, 180f, "DESTREZA (DES)",
                listOf(
                    SkillRow("Acrobacia con cuerda", "+6", Training.PROFICIENT),
                    SkillRow("Cerrajería fina", "+9", Training.EXPERTISE),
                ),
            )

            footer(s, p, 6, "ESTADÍSTICAS PERSONALIZADAS")
        }
    }

    private fun drawTraits(doc: PDDocument, p: DesktopPdfRenderingPrimitives, logo: PDFormXObject) {
        val page = extensionPage(doc)
        PDPageContentStream(doc, page).use { s ->
            extensionHeader(s, p, logo, "EXTENSIÓN - RASGOS Y CARACTERÍSTICAS", "Aster Vale")

            sectionTitle(s, p, 24f, 112f, 564f, "RASGOS Y ATRIBUTOS - CONTINUACIÓN")
            traitTable(
                s, p, 24f, 144f, 270f,
                listOf(
                    TraitRow("Portento", "Mago / Adivinación", "Sustituye una tirada apropiada por un resultado de portento disponible."),
                    TraitRow("Experiencia", "Pícaro", "Duplica el bonificador por competencia para las habilidades seleccionadas."),
                    TraitRow("Mente aguda", "Dote", "Memoria y orientación temporal extraordinarias."),
                ),
            )
            traitTable(
                s, p, 318f, 144f, 270f,
                listOf(
                    TraitRow("Ascendencia feérica", "Elfo alto", "Ventaja contra ser hechizado; la magia no puede dormirlo."),
                    TraitRow("Investigador", "Trasfondo", "Sabe dónde y cómo buscar información académica especializada."),
                    TraitRow("Código de campo", "Personalizado", "Sistema abreviado para registrar rutas, sellos y peligros."),
                ),
            )

            sectionTitle(s, p, 24f, 488f, 564f, "ESPACIO PARA RASGOS ADICIONALES")
            ruledBands(s, 24f, 520f, 564f, 188f, 8)
            footer(s, p, 7, "RASGOS Y CARACTERÍSTICAS")
        }
    }

    private fun drawResources(doc: PDDocument, p: DesktopPdfRenderingPrimitives, logo: PDFormXObject) {
        val page = extensionPage(doc)
        PDPageContentStream(doc, page).use { s ->
            extensionHeader(s, p, logo, "EXTENSIÓN - RECURSOS Y OPCIONES", "Aster Vale")

            sectionTitle(s, p, 24f, 112f, 564f, "RECURSOS")
            tableHeader(
                s, p, 24f, 142f,
                listOf(170f to "Recurso", 82f to "Actual / Máx.", 118f to "Recuperación", 86f to "Fuente", 108f to "Notas"),
            )
            val rows = listOf(
                listOf("Recuperación arcana", "1 / 1", "Descanso largo", "Mago", "Disponible"),
                listOf("Dados de portento", "1 / 2", "Descanso largo", "Mago", "Queda uno"),
                listOf("Carga del monóculo", "2 / 3", "Amanecer", "Objeto", "Sintonizado"),
                listOf("Inspiración heroica", "1 / 1", "Variable", "General", "Disponible"),
            )
            rows.forEachIndexed { i, row ->
                tableRow(s, p, 24f, 165f + i * 34f, row, listOf(170f,82f,118f,86f,108f), i)
            }
            repeat(4) { i -> blankTableRow(s, 24f, 301f + i * 28f, 564f, i) }

            sectionTitle(s, p, 24f, 432f, 564f, "OPCIONES Y ESTADOS")
            optionRow(s, p, 24f, 464f, "Tradición de Adivinación", "Mago", "Portento y capacidades relacionadas con adivinación.", 0)
            optionRow(s, p, 24f, 510f, "Herramientas de ladrón", "Competencia", "Cerraduras, trampas y dispositivos mecánicos.", 1)
            optionRow(s, p, 24f, 556f, "Monóculo rúnico", "Objeto sintonizado", "Inspección de detalles arcanos; consume cargas.", 2)
            ruledBands(s, 24f, 610f, 564f, 98f, 4)

            footer(s, p, 8, "RECURSOS Y OPCIONES")
        }
    }

    private fun drawInventory(doc: PDDocument, p: DesktopPdfRenderingPrimitives, logo: PDFormXObject) {
        val page = extensionPage(doc)
        PDPageContentStream(doc, page).use { s ->
            extensionHeader(s, p, logo, "EXTENSIÓN - INVENTARIO / EQUIPO", "Aster Vale")

            sectionTitle(s, p, 24f, 112f, 564f, "EQUIPO - CONTINUACIÓN")
            tableHeader(
                s, p, 24f, 142f,
                listOf(48f to "Cant.", 210f to "Objeto", 62f to "Peso", 96f to "Estado", 148f to "Ubicación / notas"),
            )
            val rows = listOf(
                listOf("12", "Clavos de hierro", "0,1", "Llevado", "Bolsa lateral"),
                listOf("8", "Tiza blanca", "0,0", "Llevado", "Estuche"),
                listOf("6", "Viales vacíos", "0,1", "Llevado", "Mochila"),
                listOf("2", "Tinta azul", "0,2", "Llevado", "Caja de escritura"),
                listOf("1", "Espejo de acero", "0,5", "Llevado", "Mochila"),
                listOf("1", "Manta de viaje", "3,0", "Llevado", "Mochila"),
            )
            rows.forEachIndexed { i, row ->
                tableRow(s, p, 24f, 165f + i * 31f, row, listOf(48f,210f,62f,96f,148f), i)
            }
            repeat(4) { i -> blankTableRow(s, 24f, 351f + i * 27f, 564f, i) }

            sectionTitle(s, p, 24f, 472f, 276f, "EQUIPO ESPECIAL")
            specialEquipmentRow(s, p, 24f, 504f, "Monóculo rúnico", "Sintonizado - 2/3 cargas", true, 0)
            specialEquipmentRow(s, p, 24f, 544f, "Amuleto de Liria", "Foco ceremonial", true, 1)
            specialEquipmentRow(s, p, 24f, 584f, "Daga de plata", "Arma especial", false, 2)
            ruledBands(s, 24f, 628f, 276f, 80f, 3)

            sectionTitle(s, p, 312f, 472f, 276f, "VALOR / UBICACIÓN / NOTAS")
            ruledText(
                s, p, 312f, 504f, 276f, 204f,
                listOf(
                    "Peso llevado estimado: 38,7 lb.",
                    "Gema lunar tallada: 120 po.",
                    "Broche élfico antiguo: 75 po.",
                    "Material de archivo guardado en la Academia de Liria.",
                ),
            )

            footer(s, p, 9, "INVENTARIO / EQUIPO")
        }
    }

    private fun drawSpells(doc: PDDocument, p: DesktopPdfRenderingPrimitives, logo: PDFormXObject) {
        val page = extensionPage(doc)
        PDPageContentStream(doc, page).use { s ->
            extensionHeader(s, p, logo, "EXTENSIÓN - CONJUROS", "Aster Vale")

            val x = listOf(24f, 216f, 408f)
            spellColumn(s, p, x[0], 112f, 180f, "NIVEL 1 - CONT.", "4",
                listOf("Identificar", "Dormir", "Alarma", "Comprender idiomas"))
            spellColumn(s, p, x[0], 408f, 180f, "NIVEL 2 - CONT.", "3",
                listOf("Telaraña", "Abrir", "Detectar pensamientos"))

            spellColumn(s, p, x[1], 112f, 180f, "NIVEL 3 - CONT.", "3",
                listOf("Disipar magia", "Relámpago", "Círculo mágico", "Clarividencia"))
            spellColumn(s, p, x[1], 408f, 180f, "NIVEL 4 - CONT.", "3",
                listOf("Destierro", "Confusión", "Localizar criatura"))

            spellColumn(s, p, x[2], 112f, 180f, "NIVEL 5 - CONT.", "2",
                listOf("Contacto con otro plano", "Modificar memoria", "Telepatía"))
            spellColumn(s, p, x[2], 408f, 180f, "NIVEL 6+ - CONT.", "1",
                listOf("Globo de invulnerabilidad", "Visión verdadera", "Jaula de fuerza"))

            footer(s, p, 10, "CONJUROS")
        }
    }

    private fun drawNotes(doc: PDDocument, p: DesktopPdfRenderingPrimitives, logo: PDFormXObject) {
        val page = extensionPage(doc)
        PDPageContentStream(doc, page).use { s ->
            extensionHeader(s, p, logo, "EXTENSIÓN - NOTAS", "Aster Vale")

            sectionTitle(s, p, 24f, 112f, 564f, "NOTAS")
            ruledText(
                s, p, 24f, 144f, 270f, 310f,
                listOf(
                    "Contactar a Maestra Elenya al regresar a Liria.",
                    "No entregar el mapa original a terceros.",
                    "La puerta con sello azul coincide con símbolos de las monedas antiguas.",
                ),
            )
            ruledText(
                s, p, 318f, 144f, 270f, 310f,
                listOf(
                    "Comparar el alfabeto de la puerta norte con las notas del profesor Vael.",
                    "Ruta: entrada oeste, cámara de columnas, escalera rota y galería azul.",
                    "Guardar una carga del monóculo para el archivo inferior.",
                ),
            )

            sectionTitle(s, p, 24f, 476f, 564f, "CROQUIS / MAPA")
            grid(s, 24f, 508f, 564f, 200f, 28, 10)
            footer(s, p, 11, "NOTAS")
        }
    }

    private fun customAttribute(
        s: PDPageContentStream,
        p: DesktopPdfRenderingPrimitives,
        x: Float,
        top: Float,
        width: Float,
        name: String,
        abbreviation: String,
        score: String,
        modifier: String,
        save: String,
        saveTraining: Training,
        skills: List<SkillRow>,
        note: String,
    ) {
        sectionTitle(s, p, x, top, width, "$name ($abbreviation)")
        val boxW = 52f
        statCell(s, p, x + 4f, top + 30f, boxW, 42f, "PUNT.", score)
        statCell(s, p, x + 64f, top + 30f, boxW, 42f, "MOD.", modifier)
        statCell(s, p, x + 124f, top + 30f, boxW, 42f, "SALV.", save)

        trainingMarker(s, p, x + 10f, top + 88f, saveTraining)
        text(s, p, x + 22f, top + 79f, width - 28f, 18f, "Competencia en salvación",
            PdfTypographyRole.BODY, 7.4f, 6.4f)
        hairline(s, x + 4f, top + 101f, x + width - 4f, top + 101f)

        text(s, p, x + 4f, top + 106f, width - 8f, 16f, "Habilidades gobernadas por $abbreviation",
            PdfTypographyRole.OPTIONAL_DECORATIVE, 7.1f, 6.2f, align = PdfHorizontalAlignment.CENTER)
        repeat(5) { i ->
            val rowTop = top + 128f + i * 27f
            shadeRow(s, x + 4f, rowTop, width - 8f, 24f, i)
            val skill = skills.getOrNull(i)
            if (skill != null) {
                trainingMarker(s, p, x + 11f, rowTop + 12f, skill.training)
                text(s, p, x + 23f, rowTop + 2f, width - 58f, 19f, skill.name, PdfTypographyRole.BODY, 7.8f, 6.6f)
                text(s, p, x + width - 31f, rowTop + 2f, 23f, 19f, skill.total,
                    PdfTypographyRole.NUMERIC_COMPACT, 8.5f, 7.2f, align = PdfHorizontalAlignment.RIGHT)
            }
        }

        text(s, p, x + 6f, top + 270f, width - 12f, 42f, note, PdfTypographyRole.NOTE_TEXT,
            7.6f, 6.5f, wrap = true, maxLines = 3, vertical = PdfVerticalAlignment.TOP)
        ruledBands(s, x + 4f, top + 316f, width - 8f, 88f, 4)
    }

    private fun linkedSkillColumn(
        s: PDPageContentStream,
        p: DesktopPdfRenderingPrimitives,
        x: Float,
        top: Float,
        width: Float,
        title: String,
        skills: List<SkillRow>,
    ) {
        sectionTitle(s, p, x, top, width, title)
        repeat(7) { i ->
            val rowTop = top + 30f + i * 27f
            shadeRow(s, x, rowTop, width, 24f, i)
            val skill = skills.getOrNull(i)
            if (skill != null) {
                trainingMarker(s, p, x + 9f, rowTop + 12f, skill.training)
                text(s, p, x + 21f, rowTop + 2f, width - 54f, 19f, skill.name,
                    PdfTypographyRole.BODY, 7.7f, 6.5f)
                text(s, p, x + width - 29f, rowTop + 2f, 22f, 19f, skill.total,
                    PdfTypographyRole.NUMERIC_COMPACT, 8.4f, 7.2f, align = PdfHorizontalAlignment.RIGHT)
            }
        }
    }

    private fun traitTable(
        s: PDPageContentStream,
        p: DesktopPdfRenderingPrimitives,
        x: Float,
        top: Float,
        width: Float,
        rows: List<TraitRow>,
    ) {
        repeat(7) { i ->
            val rowTop = top + i * 46f
            shadeRow(s, x, rowTop, width, 42f, i)
            rows.getOrNull(i)?.let { row ->
                text(s, p, x + 4f, rowTop + 2f, 92f, 18f, row.name, PdfTypographyRole.SPELL_NAME, 8.4f, 7.2f)
                text(s, p, x + 100f, rowTop + 2f, width - 104f, 18f, row.source,
                    PdfTypographyRole.OPTIONAL_DECORATIVE, 7f, 6f, align = PdfHorizontalAlignment.RIGHT)
                text(s, p, x + 4f, rowTop + 20f, width - 8f, 20f, row.description,
                    PdfTypographyRole.BODY, 7.4f, 6.3f, wrap = true, maxLines = 2,
                    vertical = PdfVerticalAlignment.TOP)
            }
        }
    }

    private fun optionRow(
        s: PDPageContentStream,
        p: DesktopPdfRenderingPrimitives,
        x: Float,
        top: Float,
        name: String,
        source: String,
        description: String,
        index: Int,
    ) {
        shadeRow(s, x, top, 564f, 42f, index)
        text(s, p, x + 5f, top + 2f, 175f, 18f, name, PdfTypographyRole.SPELL_NAME, 8.5f, 7.2f)
        text(s, p, x + 185f, top + 2f, 120f, 18f, source, PdfTypographyRole.OPTIONAL_DECORATIVE, 7.3f, 6.2f)
        text(s, p, x + 310f, top + 2f, 249f, 36f, description, PdfTypographyRole.BODY, 7.7f, 6.5f,
            wrap = true, maxLines = 2, vertical = PdfVerticalAlignment.TOP)
    }

    private fun specialEquipmentRow(
        s: PDPageContentStream,
        p: DesktopPdfRenderingPrimitives,
        x: Float,
        top: Float,
        name: String,
        note: String,
        checked: Boolean,
        index: Int,
    ) {
        shadeRow(s, x, top, 276f, 36f, index)
        marker(s, p, x + 9f, top + 18f, 8f, if (checked) PdfMarkerKind.CHECK else PdfMarkerKind.SQUARE_OUTLINE)
        text(s, p, x + 20f, top + 2f, 104f, 18f, name, PdfTypographyRole.SPELL_NAME, 8f, 6.8f)
        text(s, p, x + 126f, top + 2f, 145f, 30f, note, PdfTypographyRole.BODY, 7.4f, 6.3f,
            wrap = true, maxLines = 2, vertical = PdfVerticalAlignment.TOP)
    }

    private fun spellColumn(
        s: PDPageContentStream,
        p: DesktopPdfRenderingPrimitives,
        x: Float,
        top: Float,
        width: Float,
        title: String,
        slots: String,
        spells: List<String>,
    ) {
        sectionTitle(s, p, x, top, width, title)
        statCell(s, p, x + width - 51f, top + 28f, 47f, 34f, "ESPACIOS", slots)
        text(s, p, x + 4f, top + 34f, width - 63f, 12f, "ESPACIOS GASTADOS", PdfTypographyRole.OPTIONAL_DECORATIVE,
            6.2f, 5.5f)
        repeat(3) { i -> marker(s, p, x + 18f + i * 17f, top + 57f, 8f, PdfMarkerKind.OVAL_OUTLINE) }

        repeat(9) { i ->
            val rowTop = top + 75f + i * 23f
            shadeRow(s, x, rowTop, width, 20f, i)
            marker(s, p, x + 9f, rowTop + 10f, 7f, PdfMarkerKind.SQUARE_OUTLINE)
            val spell = spells.getOrNull(i).orEmpty()
            text(s, p, x + 20f, rowTop + 1f, width - 24f, 17f, spell, PdfTypographyRole.SPELL_NAME, 8f, 6.8f)
        }
    }

    private fun extensionHeader(
        s: PDPageContentStream,
        p: DesktopPdfRenderingPrimitives,
        logo: PDFormXObject,
        title: String,
        name: String,
    ) {
        // Reuse the exact owner-source logo/branding crop while drawing the extension layout natively.
        s.saveGraphicsState()
        s.addRect(18f, H - 82f, 132f, 64f)
        s.clip()
        s.drawForm(logo)
        s.restoreGraphicsState()

        text(s, p, 164f, 27f, 424f, 22f, title, PdfTypographyRole.OPTIONAL_DECORATIVE, 13f, 10.5f,
            align = PdfHorizontalAlignment.CENTER)
        hairline(s, 164f, 54f, 588f, 54f)
        text(s, p, 164f, 58f, 424f, 18f, name, PdfTypographyRole.HANDWRITTEN_NAME, 11f, 9f,
            align = PdfHorizontalAlignment.CENTER)
    }

    private fun sectionTitle(
        s: PDPageContentStream,
        p: DesktopPdfRenderingPrimitives,
        x: Float,
        top: Float,
        width: Float,
        title: String,
    ) {
        text(s, p, x, top, width, 20f, title, PdfTypographyRole.OPTIONAL_DECORATIVE, 9.2f, 7.6f,
            align = PdfHorizontalAlignment.CENTER)
        hairline(s, x, top + 22f, x + width, top + 22f)
    }

    private fun statCell(
        s: PDPageContentStream,
        p: DesktopPdfRenderingPrimitives,
        x: Float,
        top: Float,
        width: Float,
        height: Float,
        label: String,
        value: String,
    ) {
        strokeRect(s, x, top, width, height, 0.65f)
        text(s, p, x + 3f, top + 3f, width - 6f, 10f, label, PdfTypographyRole.OPTIONAL_DECORATIVE, 6.2f, 5.3f,
            align = PdfHorizontalAlignment.CENTER)
        text(s, p, x + 4f, top + 14f, width - 8f, height - 17f, value, PdfTypographyRole.PRIMARY_VALUE, 13f, 10f,
            align = PdfHorizontalAlignment.CENTER)
    }

    private fun tableHeader(
        s: PDPageContentStream,
        p: DesktopPdfRenderingPrimitives,
        x: Float,
        top: Float,
        columns: List<Pair<Float, String>>,
    ) {
        var cursor = x
        columns.forEach { (width, title) ->
            text(s, p, cursor + 2f, top, width - 4f, 18f, title, PdfTypographyRole.OPTIONAL_DECORATIVE, 7f, 6f,
                align = PdfHorizontalAlignment.CENTER)
            cursor += width
        }
        hairline(s, x, top + 20f, cursor, top + 20f)
    }

    private fun tableRow(
        s: PDPageContentStream,
        p: DesktopPdfRenderingPrimitives,
        x: Float,
        top: Float,
        values: List<String>,
        widths: List<Float>,
        index: Int,
    ) {
        shadeRow(s, x, top, widths.sum(), 30f, index)
        var cursor = x
        values.forEachIndexed { i, value ->
            text(
                s, p, cursor + 3f, top + 2f, widths[i] - 6f, 25f, value,
                if (i == 1 || i == 0) PdfTypographyRole.BODY else PdfTypographyRole.COMPACT_TABLE,
                if (i == 1) 8.2f else 7.5f, 6.4f,
                align = if (i == 0 || i == 2) PdfHorizontalAlignment.CENTER else PdfHorizontalAlignment.LEFT,
            )
            cursor += widths[i]
        }
    }

    private fun blankTableRow(s: PDPageContentStream, x: Float, top: Float, width: Float, index: Int) {
        shadeRow(s, x, top, width, 24f, index)
    }

    private fun ruledText(
        s: PDPageContentStream,
        p: DesktopPdfRenderingPrimitives,
        x: Float,
        top: Float,
        width: Float,
        height: Float,
        paragraphs: List<String>,
    ) {
        val rowHeight = 22f
        val rows = (height / rowHeight).toInt()
        repeat(rows) { i -> shadeRow(s, x, top + i * rowHeight, width, rowHeight - 2f, i) }
        paragraphs.forEachIndexed { i, paragraph ->
            val paragraphTop = top + i * 66f + 2f
            text(s, p, x + 4f, paragraphTop, width - 8f, 60f, paragraph, PdfTypographyRole.NOTE_TEXT,
                8.1f, 7f, wrap = true, maxLines = 3, vertical = PdfVerticalAlignment.TOP)
        }
    }

    private fun ruledBands(
        s: PDPageContentStream,
        x: Float,
        top: Float,
        width: Float,
        height: Float,
        rows: Int,
    ) {
        val rowHeight = height / rows
        repeat(rows) { i -> shadeRow(s, x, top + i * rowHeight, width, rowHeight - 2f, i) }
    }

    private fun shadeRow(
        s: PDPageContentStream,
        x: Float,
        top: Float,
        width: Float,
        height: Float,
        index: Int,
    ) {
        if (index % 2 == 0) fillRect(s, x, top, width, height, BAND_FILL)
        hairline(s, x, top + height + 2f, x + width, top + height + 2f)
    }

    private fun grid(
        s: PDPageContentStream,
        x: Float,
        top: Float,
        width: Float,
        height: Float,
        columns: Int,
        rows: Int,
    ) {
        val y = H - top - height
        s.saveGraphicsState()
        s.setStrokingColor(GRID_COLOR)
        s.setLineWidth(0.35f)
        s.addRect(x, y, width, height)
        s.stroke()
        repeat(columns - 1) { i ->
            val xx = x + width * (i + 1) / columns
            s.moveTo(xx, y)
            s.lineTo(xx, y + height)
        }
        repeat(rows - 1) { i ->
            val yy = y + height * (i + 1) / rows
            s.moveTo(x, yy)
            s.lineTo(x + width, yy)
        }
        s.stroke()
        s.restoreGraphicsState()
    }

    private fun trainingMarker(
        s: PDPageContentStream,
        p: DesktopPdfRenderingPrimitives,
        centerX: Float,
        centerTop: Float,
        training: Training,
    ) {
        marker(
            s, p, centerX, centerTop, 8f,
            when (training) {
                Training.NONE -> PdfMarkerKind.CIRCLE_OUTLINE
                Training.PROFICIENT -> PdfMarkerKind.CHECK
                Training.EXPERTISE -> PdfMarkerKind.DOUBLE_CHECK
            },
        )
    }

    private fun marker(
        s: PDPageContentStream,
        p: DesktopPdfRenderingPrimitives,
        centerX: Float,
        centerTop: Float,
        size: Float,
        kind: PdfMarkerKind,
    ) {
        p.drawMarker(
            s,
            centerX = centerX,
            centerY = H - centerTop,
            sizePt = size,
            kind = kind,
            family = PdfSymbolFamily.V1_DERIVED,
        )
    }

    private fun text(
        s: PDPageContentStream,
        p: DesktopPdfRenderingPrimitives,
        x: Float,
        top: Float,
        width: Float,
        height: Float,
        value: String,
        role: PdfTypographyRole,
        preferred: Float,
        minimum: Float,
        wrap: Boolean = false,
        maxLines: Int = 1,
        align: PdfHorizontalAlignment = PdfHorizontalAlignment.LEFT,
        vertical: PdfVerticalAlignment = PdfVerticalAlignment.CENTER,
    ) {
        val result = p.drawTextBox(
            s,
            PdfTextBoxSpec(
                rect = PdfRect(x, H - top - height, width, height),
                text = value,
                role = role,
                preferredSizePt = preferred,
                minimumSizePt = minimum,
                horizontalAlignment = align,
                verticalAlignment = vertical,
                wrapPolicy = if (wrap) PdfWrapPolicy.WORD_WRAP else PdfWrapPolicy.SINGLE_LINE,
                maximumLines = maxLines,
                horizontalPaddingPt = 0.7f,
                verticalPaddingPt = 0.4f,
            ),
        )
        if (result.hasOverflow) {
            overflowDiagnostics += "value='$value' overflow='${result.overflowText}'"
        }
    }

    private fun footer(
        s: PDPageContentStream,
        p: DesktopPdfRenderingPrimitives,
        pageNumber: Int,
        label: String,
    ) {
        hairline(s, 24f, 744f, 588f, 744f)
        text(s, p, 24f, 749f, 420f, 14f, label, PdfTypographyRole.OPTIONAL_DECORATIVE, 7f, 6f)
        text(s, p, 516f, 749f, 72f, 14f, "PÁG. $pageNumber", PdfTypographyRole.OPTIONAL_DECORATIVE, 7f, 6f,
            align = PdfHorizontalAlignment.RIGHT)
    }

    private fun fillRect(s: PDPageContentStream, x: Float, top: Float, width: Float, height: Float, color: Color) {
        s.saveGraphicsState()
        s.setNonStrokingColor(color)
        s.addRect(x, H - top - height, width, height)
        s.fill()
        s.restoreGraphicsState()
    }

    private fun strokeRect(s: PDPageContentStream, x: Float, top: Float, width: Float, height: Float, lineWidth: Float) {
        s.saveGraphicsState()
        s.setStrokingColor(Color.BLACK)
        s.setLineWidth(lineWidth)
        s.addRect(x, H - top - height, width, height)
        s.stroke()
        s.restoreGraphicsState()
    }

    private fun hairline(s: PDPageContentStream, x1: Float, top1: Float, x2: Float, top2: Float) {
        s.saveGraphicsState()
        s.setStrokingColor(LINE_COLOR)
        s.setLineWidth(0.35f)
        s.moveTo(x1, H - top1)
        s.lineTo(x2, H - top2)
        s.stroke()
        s.restoreGraphicsState()
    }

    private fun extensionPage(doc: PDDocument): PDPage =
        PDPage(PDRectangle(W, H)).also(doc::addPage)

    private fun assertImagesEqual(expected: BufferedImage, actual: BufferedImage, message: String) {
        assertEquals(expected.width, actual.width, message)
        assertEquals(expected.height, actual.height, message)
        val width = expected.width
        val a = IntArray(width)
        val b = IntArray(width)
        repeat(expected.height) { y ->
            expected.getRGB(0, y, width, 1, a, 0, width)
            actual.getRGB(0, y, width, 1, b, 0, width)
            assertTrue(a.contentEquals(b), "$message First differing raster row: $y")
        }
    }

    private fun resource(path: String) =
        requireNotNull(DesktopPcSheetCustomV1ExtendedFamilyRun1Test::class.java.classLoader.getResourceAsStream(path)) {
            "Missing test resource: $path"
        }

    private data class SkillRow(val name: String, val total: String, val training: Training)
    private data class TraitRow(val name: String, val source: String, val description: String)
    private enum class Training { NONE, PROFICIENT, EXPERTISE }

    private companion object {
        const val W = 612f
        const val H = 792f
        const val BASELINE_COMPARE_DPI = 120f
        const val TEMPLATE = "character-sheets/templates/Hoja de PJ - 5.0 - Simkin.pdf"

        val BAND_FILL = Color(224, 224, 224)
        val LINE_COLOR = Color(132, 132, 132)
        val GRID_COLOR = Color(198, 198, 198)

        val CUSTOM_V1_EXTENSION_THEME = PdfTypographyTheme(
            id = "custom-v1-extended-family-run1",
            resourcesByRole = mapOf(
                PdfTypographyRole.CHARACTER_NAME to "fonts/pdf/text/Kalam-Bold.ttf",
                PdfTypographyRole.HANDWRITTEN_NAME to "fonts/pdf/text/Kalam-Bold.ttf",
                PdfTypographyRole.PRIMARY_VALUE to "fonts/pdf/text/BarlowCondensed-Bold.ttf",
                PdfTypographyRole.SECONDARY_VALUE to "fonts/pdf/text/FiraSans-SemiBold.ttf",
                PdfTypographyRole.BODY to "fonts/pdf/text/FiraSans-Regular.ttf",
                PdfTypographyRole.COMPACT_TABLE to "fonts/pdf/text/FiraSans-Regular.ttf",
                PdfTypographyRole.NUMERIC_COMPACT to "fonts/pdf/text/FiraSans-SemiBold.ttf",
                PdfTypographyRole.NOTE_TEXT to "fonts/pdf/text/FiraSans-Regular.ttf",
                PdfTypographyRole.SPELL_NAME to "fonts/pdf/text/FiraSans-SemiBold.ttf",
                PdfTypographyRole.OPTIONAL_DECORATIVE to "fonts/pdf/text/BarlowCondensed-Bold.ttf",
            ),
        )
    }
}
