// GENERATED by scripts/generate_android_pc_sheet_renderer.py from DesktopPortraitRenderer.kt.
// Do not edit this file directly; edit the Desktop renderer authority and regenerate.
package io.github.mrsimkin.dndcustomaid.android.pdf

import io.github.mrsimkin.dndcustomaid.shared.character.PcSheetPdfRenderPlan
import io.github.mrsimkin.dndcustomaid.shared.character.PcSheetPortraitFitMode
import io.github.mrsimkin.dndcustomaid.shared.character.PcSheetVisualFamily
import com.tom_roush.pdfbox.pdmodel.PDDocument
import com.tom_roush.pdfbox.pdmodel.PDPageContentStream
import com.tom_roush.pdfbox.pdmodel.PDPageContentStream.AppendMode
import com.tom_roush.pdfbox.pdmodel.graphics.image.PDImageXObject
import com.tom_roush.pdfbox.text.PDFTextStripper

/**
 * Platform-owned portrait byte -> PDF overlay boundary.
 *
 * The shared render plan deliberately carries only the stable portrait reference, local-availability
 * fact and selected fit mode. Android resolves local bytes at export time and overlays them into the
 * already-approved family frame without changing the canonical character model or requiring network
 * access. Invalid/unreadable local bytes degrade to a blank portrait rather than blocking export.
 */
internal class AndroidPortraitRenderer(
    private val document: PDDocument,
) {
    private val primitives = AndroidPdfRenderingPrimitives(AndroidPdfFontRegistry(document))

    fun overlay(
        plan: PcSheetPdfRenderPlan,
        bytes: ByteArray,
    ): Boolean {
        val target = targetFor(plan.request.visualFamily).let { staticTarget ->
            if (plan.request.visualFamily == PcSheetVisualFamily.CLASSIC_DND_STYLE) {
                staticTarget.copy(pageIndex = classicPortraitPageIndex())
            } else {
                staticTarget
            }
        }
        if (target.pageIndex !in 0 until document.numberOfPages) return false

        val image = runCatching {
            PDImageXObject.createFromByteArray(document, bytes, "pc-portrait")
        }.getOrNull() ?: return false

        val page = document.getPage(target.pageIndex)
        PDPageContentStream(document, page, AppendMode.APPEND, true, true).use { stream ->
            stream.saveGraphicsState()
            target.clipPolygon?.let { polygon ->
                val first = polygon.first()
                stream.moveTo(first.x, first.y)
                polygon.drop(1).forEach { point -> stream.lineTo(point.x, point.y) }
                stream.closePath()
                stream.clip()
            }

            primitives.drawImage(
                stream = stream,
                image = image,
                rect = target.rect,
                mode = when (plan.snapshot.portrait.fitMode) {
                    PcSheetPortraitFitMode.CROP_TO_FILL -> PdfImageFitMode.CROP_FILL
                    PcSheetPortraitFitMode.FIT_ENTIRE_IMAGE -> PdfImageFitMode.FIT_ENTIRE
                },
            )
            stream.restoreGraphicsState()
        }
        return true
    }

    private fun classicPortraitPageIndex(): Int {
        for (pageIndex in 0 until document.numberOfPages) {
            val text = PDFTextStripper().apply {
                startPage = pageIndex + 1
                endPage = pageIndex + 1
            }.getText(document)
            if (text.contains("ASPECTO", ignoreCase = true)) {
                return pageIndex
            }
        }
        return 1
    }

    private fun targetFor(family: PcSheetVisualFamily): PortraitTarget = when (family) {
        PcSheetVisualFamily.CLASSIC_DND_STYLE -> PortraitTarget(
            pageIndex = 1,
            rect = rectFromTop(39f, 139f, 196f, 144f),
        )

        PcSheetVisualFamily.CUSTOM_V1 -> PortraitTarget(
            pageIndex = 0,
            rect = rectFromTop(457f, 31f, 128f, 131f),
        )

        PcSheetVisualFamily.CUSTOM_V2_PER_ATTRIBUTE -> {
            val polygonTopCoordinates = listOf(
                TopPoint(225f, 33f),
                TopPoint(305f, 33f),
                TopPoint(314f, 40f),
                TopPoint(339f, 108f),
                TopPoint(334f, 114f),
                TopPoint(326f, 119f),
                TopPoint(204f, 119f),
                TopPoint(196f, 114f),
                TopPoint(191f, 108f),
                TopPoint(216f, 40f),
            )
            PortraitTarget(
                pageIndex = 0,
                rect = rectFromTop(191f, 33f, 148f, 86f),
                clipPolygon = polygonTopCoordinates.map(::toPdfPoint),
            )
        }

        PcSheetVisualFamily.CUSTOM_V2_PER_ABILITY -> {
            // Source page 2 intentionally has a taller portrait field than page 1. Its handwritten
            // name banner begins near top=177 pt, so keep the image inside the field above it.
            val polygonTopCoordinates = listOf(
                TopPoint(225f, 33f),
                TopPoint(305f, 33f),
                TopPoint(314f, 40f),
                TopPoint(339f, 108f),
                TopPoint(336f, 139f),
                TopPoint(329f, 150f),
                TopPoint(314f, 165f),
                TopPoint(216f, 165f),
                TopPoint(201f, 150f),
                TopPoint(194f, 139f),
                TopPoint(191f, 108f),
                TopPoint(216f, 40f),
            )
            PortraitTarget(
                pageIndex = 0,
                rect = rectFromTop(191f, 33f, 148f, 132f),
                clipPolygon = polygonTopCoordinates.map(::toPdfPoint),
            )
        }
    }

    private fun rectFromTop(
        x: Float,
        top: Float,
        width: Float,
        height: Float,
    ): PdfRect = PdfRect(
        x = x,
        y = PAGE_HEIGHT - top - height,
        width = width,
        height = height,
    )

    private fun toPdfPoint(point: TopPoint): PdfPoint =
        PdfPoint(point.x, PAGE_HEIGHT - point.top)

    private data class PortraitTarget(
        val pageIndex: Int,
        val rect: PdfRect,
        val clipPolygon: List<PdfPoint>? = null,
    )

    private data class TopPoint(
        val x: Float,
        val top: Float,
    )

    private data class PdfPoint(
        val x: Float,
        val y: Float,
    )

    private companion object {
        const val PAGE_HEIGHT = 792f
    }
}
