#!/usr/bin/env python3
from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SOURCE_ROOT = ROOT / "desktopApp/src/main/kotlin/io/github/mrsimkin/dndcustomaid/desktop"
OUTPUT_ROOT = ROOT / "androidApp/src/main/kotlin/io/github/mrsimkin/dndcustomaid/android/pdf"
SOURCE_NAMES = [
    "DesktopPdfRenderingPrimitives.kt",
    "DesktopClassicRenderer.kt",
    "DesktopCustomV1HybridRenderer.kt",
    "DesktopCustomV1ExtendedRenderer.kt",
    "DesktopCustomV2SharedBaseRenderer.kt",
    "DesktopCustomV2ExtendedRenderer.kt",
    "DesktopPcSheetTemplateProofRenderer.kt",
    "DesktopPcSheetVisualCompletionRenderer.kt",
    "DesktopSpellbookRenderer.kt",
    "DesktopPortraitRenderer.kt",
    "DesktopPcSheetWholeDraftRenderer.kt",
]

def transform(source: str, source_name: str) -> str:
    rendered = source
    rendered = rendered.replace(
        "package io.github.mrsimkin.dndcustomaid.desktop",
        "package io.github.mrsimkin.dndcustomaid.android.pdf",
    )
    rendered = rendered.replace("Desktop", "Android")
    rendered = rendered.replace("org.apache.pdfbox", "com.tom_roush.pdfbox")
    rendered = rendered.replace(
        "import java.awt.Color",
        "import com.tom_roush.harmony.awt.AWTColor as Color",
    )
    rendered = rendered.replace(
        "java.awt.Color",
        "com.tom_roush.harmony.awt.AWTColor",
    )
    rendered = rendered.replace(
        "import java.awt.geom.AffineTransform",
        "import com.tom_roush.harmony.awt.geom.AffineTransform",
    )
    rendered = rendered.replace(
        "import java.awt.image.BufferedImage",
        "import android.graphics.Bitmap",
    )
    rendered = rendered.replace("import com.tom_roush.pdfbox.Loader\n", "")
    rendered = rendered.replace("Loader.loadPDF(", "PDDocument.load(")
    rendered = re.sub(
        r"Android[A-Za-z0-9_]+::class\.java\.classLoader\.getResourceAsStream\(([^)]+)\)",
        r"AndroidPcSheetAssetLoader.open(\1)",
        rendered,
    )
    rendered = rendered.replace(
        "BufferedImage(width, height, BufferedImage.TYPE_INT_ARGB)",
        "Bitmap.createBitmap(width, height, Bitmap.Config.ARGB_8888)",
    )
    rendered = rendered.replace("transparent.setRGB(", "transparent.setPixel(")
    rendered = rendered.replace("sourceImage.getRGB(", "sourceImage.getPixel(")

    forbidden = [
        "org.apache.pdfbox",
        "java.awt.",
        "BufferedImage",
        "Loader.loadPDF",
        "classLoader.getResourceAsStream",
        "package io.github.mrsimkin.dndcustomaid.desktop",
    ]
    leftovers = [token for token in forbidden if token in rendered]
    if leftovers:
        raise RuntimeError(
            f"{source_name}: unsupported Desktop-only tokens remain: {', '.join(leftovers)}"
        )
    return (
        f"// GENERATED by scripts/generate_android_pc_sheet_renderer.py from {source_name}.\n"
        "// Do not edit this file directly; edit the Desktop renderer authority and regenerate.\n"
        + rendered
    )

def expected_files() -> dict[Path, str]:
    result: dict[Path, str] = {}
    for source_name in SOURCE_NAMES:
        source_path = SOURCE_ROOT / source_name
        output_name = source_name.replace("Desktop", "Android", 1)
        result[OUTPUT_ROOT / output_name] = transform(
            source_path.read_text(encoding="utf-8"),
            source_name,
        )
    return result

def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    expected = expected_files()
    if args.check:
        stale: list[str] = []
        for path, content in expected.items():
            if not path.exists() or path.read_text(encoding="utf-8") != content:
                stale.append(str(path.relative_to(ROOT)))
        if stale:
            print("Android PC sheet renderer port is stale:", file=sys.stderr)
            for path in stale:
                print(f" - {path}", file=sys.stderr)
            print("Run: python3 scripts/generate_android_pc_sheet_renderer.py", file=sys.stderr)
            return 1
        print(f"Android PC sheet renderer sync guard PASS ({len(expected)} generated files).")
        return 0
    OUTPUT_ROOT.mkdir(parents=True, exist_ok=True)
    for path, content in expected.items():
        path.write_text(content, encoding="utf-8")
        print(f"generated {path.relative_to(ROOT)}")
    return 0

if __name__ == "__main__":
    raise SystemExit(main())
